### Import Libraries

In [21]:
import numpy as np
import pandas as pd

### Reading Dataset

In [22]:
#setting option to display all columns from data file
pd.set_option('display.max_columns', None)
data=pd.read_csv('fifa21 raw data v2.csv')
data.sample(10)

C:\Users\Basit Hussain\AppData\Local\Temp\ipykernel_2316\3118632006.py:3: DtypeWarning: Columns (75) have mixed types. Specify dtype option on import or set low_memory=False.
  data=pd.read_csv('fifa21 raw data v2.csv')


ID           Name                LongName  \
13848  257998  Victor Méndez  Victor Méndez Exposito   
12269  240978    D. Mandroiu          Danny Mandroiu   
5877   234111    D. Turnbull          David Turnbull   
8046   167841     C. Maguire           Chris Maguire   
18446  258693       E. Mirus              Eryk Mirus   
17659  251738       M. Chada         Madanapal Chada   
16282  247356       K. Smith              Kyle Smith   
15475  258041          Novoa              Hugo Novoa   
10224  226710    G. Scamacca       Gianluca Scamacca   
17427  228784      Q. Lajami            Qasem Lajami   

                                               photoUrl  \
13848  https://cdn.sofifa.com/players/257/998/21_60.png   
12269  https://cdn.sofifa.com/players/240/978/21_60.png   
5877   https://cdn.sofifa.com/players/234/111/21_60.png   
8046   https://cdn.sofifa.com/players/167/841/21_60.png   
18446  https://cdn.sofifa.com/players/258/693/21_60.png   
17659  https://cdn.sofifa.com/players/251/738/21_60.png   
16282  https://cdn.sofifa.com/players/247/356/21_60.png   
15475  https://cdn.sofifa.com/players/258/041/21_60.png   
10224  https://cdn.sofifa.com/players/226/710/21_60.png   
17427  https://cdn.sofifa.com/players/228/784/21_60.png   

                                               playerUrl          Nationality  \
13848  http://sofifa.com/player/257998/victor-mendez-...                Spain   
12269  http://sofifa.com/player/240978/danny-mandroiu...  Republic of Ireland   
5877   http://sofifa.com/player/234111/david-turnbull...             Scotland   
8046   http://sofifa.com/player/167841/chris-maguire/...             Scotland   
18446  http://sofifa.com/player/258693/eryk-mirus/210...               Poland   
17659  http://sofifa.com/player/251738/madanapal-chad...                India   
16282  http://sofifa.com/player/247356/kyle-smith/210...        United States   
15475  http://sofifa.com/player/258041/hugo-novoa/210...                Spain   
10224  http://sofifa.com/player/226710/gianluca-scama...                Italy   
17427  http://sofifa.com/player/228784/qasem-lajami/2...         Saudi Arabia   

       Age  ↓OVA  POT              Contract Positions Height Weight  \
13848   20    62   76           2020 ~ 2024        GK  188cm   80kg   
12269   21    63   73           2018 ~ 2020       CAM  178cm   73kg   
5877    20    69   82           2020 ~ 2024   CM, CAM  185cm   75kg   
8046    31    67   67           2018 ~ 2021   RW, CAM  170cm   68kg   
18446   16    52   72           2020 ~ 2023        GK  186cm   75kg   
17659   27    55   55                  Free        ST  178cm   77kg   
16282   28    58   58           2018 ~ 2023        RB  180cm   81kg   
15475   17    60   78           2020 ~ 2021        ST  176cm   65kg   
10224   21    65   78  Jun 30, 2021 On Loan        ST  195cm   85kg   
17427   24    56   65           2019 ~ 2024        CB  178cm   75kg   

      Preferred Foot  BOV Best Position     Joined Loan Date End  Value  Wage  \
13848          Right   62            GK   1-Jul-20           NaN  €850K  €950   
12269          Right   65           CAM   3-Dec-18           NaN  €1.1M  €600   
5877           Right   72           CAM  27-Aug-20           NaN  €3.3M  €17K   
8046           Right   67            RW   1-Jul-18           NaN  €850K   €6K   
18446          Right   52            GK  27-Aug-20           NaN  €190K  €500   
17659          Right   57            RM  12-Jul-19           NaN     €0    €0   
16282          Right   58            RB  19-Dec-18           NaN  €180K   €1K   
15475          Right   62            ST   1-Jul-20           NaN  €625K   €1K   
10224          Right   67            ST  31-Jan-17     30-Jun-21  €1.8M   €7K   
17427           Left   58            CB   1-Jul-19           NaN  €300K   €4K   

      Release Clause  Attacking  Crossing  Finishing  Heading Accuracy  \
13848          €1.3M         79        12          7                13   
12269          €1.1M        29

In [23]:
data.shape #(rows,columns)

(18979, 76)

In [24]:
# in order to know data types and count of elements we use info method
data.info() 
#observe those columns having count less than rows i.e they have null values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 76 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   ID                18979 non-null  int64 
 1   Name              18979 non-null  object
 2   LongName          18979 non-null  object
 3   photoUrl          18979 non-null  object
 4   playerUrl         18979 non-null  object
 5   Nationality       18979 non-null  object
 6   Age               18979 non-null  int64 
 7   ↓OVA              18979 non-null  int64 
 8   POT               18979 non-null  int64 
 9   Contract          18979 non-null  object
 10  Positions         18979 non-null  object
 11  Height            18979 non-null  object
 12  Weight            18979 non-null  object
 13  Preferred Foot    18979 non-null  object
 14  BOV               18979 non-null  int64 
 15  Best Position     18979 non-null  object
 16  Joined            18979 non-null  object
 17  Loan Date En

In [25]:
# in above output column 17 (Loan Data end ) and column 75(hits) have null values

# Data Cleaning

### Create a copy of DataFrame

In [26]:
fifa21=data.copy()
fifa21.sample(4)

ID          Name                 LongName  \
984    198230        Germán  Germán Sánchez Barahona   
13443  222592  Kim Dong Jin             Dong Jin Kim   
15440  256723      M. Nguer          Mor Talla Nguer   
4522   253695     L. Takács          Ladislav Takács   

                                               photoUrl  \
984    https://cdn.sofifa.com/players/198/230/21_60.png   
13443  https://cdn.sofifa.com/players/222/592/21_60.png   
15440  https://cdn.sofifa.com/players/256/723/21_60.png   
4522   https://cdn.sofifa.com/players/253/695/21_60.png   

                                               playerUrl     Nationality  Age  \
984    http://sofifa.com/player/198230/german-sanchez...           Spain   33   
13443  http://sofifa.com/player/222592/dong-jin-kim/2...  Korea Republic   27   
15440  http://sofifa.com/player/256723/mor-talla-ngue...         Senegal   22   
4522   http://sofifa.com/player/253695/ladislav-takac...  Czech Republic   23   

       ↓OVA  POT     Contract Positions Height Weight Preferred Foot  BOV  \
984      77   77  2017 ~ 2022        CB  187cm   82kg          Right   77   
13443    62   63  2014 ~ 2025    LB, CB  177cm   74kg           Left   63   
15440    60   69  2019 ~ 2021    RW, ST  176cm   61kg          Right   61   
4522     71   75  2019 ~ 2022   CDM, CB  190cm   84kg          Right   73   

      Best Position     Joined Loan Date End  Value  Wage Release Clause  \
984              CB   3-Jul-17           NaN    €5M  €25K          €8.8M   
13443            CB   1-Jan-14           NaN  €425K   €2K          €398K   
15440           CAM  22-Jul-19           NaN  €550K  €950          €634K   
4522             CB   3-Sep-19           NaN  €2.4M  €500          €6.4M   

       Attacking  Crossing  Finishing  Heading Accuracy  Short Passing  \
984          257        42         40                79             76   
13443        183        46         21                55             36   
15440        262        50         60                45             55   
4522         295        41         54                74             72   

       Volleys  Skill  Dribbling  Curve  FK Accuracy  Long Passing  \
984         20    249         51     28           35            65   
13443       25    188         34     26           34            35   
15440       52    267         68     46           42            46   
4522        54    268         60     44           32            66   

       Ball Control  Movement  Acceleration  Sprint Speed  Agility  Reactions  \
984              70       248            44            57       39         64   
13443            59       322            66            70       59         59   
15440            65       335            73            75       68         41   
4522             66       293            61            60       60         66   

       Balance  Power  Shot Power  Jumping  Stamina  Strength  Long Shots  \
984         44    312          65       68       77        81          21   
13443       68    268          21       76       71        75          25   
15440       78    266          67       46       55        46          52   
4522        46    334          72       57       71        84          50   

       Mentality  Aggression  Interceptions  Positioning  Vision  Penalties  \
984          293          80             79           40      56         38   
13443        225          52             66           47      34         26   
15440        238          43             29           56      57         53   
4522         282          70             69           42      61         40   

       Composure  Defending  Marking  Standing Tackle  Sliding Tackle  \
984           62        233       74               81              78   
13443         69        186       55               67              64   
15440         52         78       25               28              25   
4522          60        212       69               73      

### 1. ID

Unique identifier for each player.

In [27]:
fifa21['ID'].dtype

dtype('int64')

In [28]:
fifa21['ID'].unique

<bound method Series.unique of 0        158023
1         20801
2        200389
3        192985
4        190871
          ...  
18974    247223
18975    258760
18976    252757
18977    243790
18978    252520
Name: ID, Length: 18979, dtype: int64>

### 2. Name

Player's name

### 3. LongName

Player's full name

### 4. photoURL

URL to player's photo

### 5. playerURL

URL to player's profile

### 6. Nationality

Player's nationality

### 7. Age

Player's age in years

### 8. OVA - Overall Rating (0-100)

It is a rating system used to represent a player's overall abilities and skills in the game.

### 9. POT - Potential Rating(0-100)

Represent a player's potential to develop and improve their abilities and skills over time.

### 10. Club

Current Club of the player

In [29]:
fifa21['Club'].dtype

KeyError: 'Club'

### 11. Contract column

In [30]:
fifa21['Contract'].dtype

dtype('O')

In [31]:
fifa21['Contract'].unique()

array(['2004 ~ 2021', '2018 ~ 2022', '2014 ~ 2023', '2015 ~ 2023',
       '2017 ~ 2022', '2017 ~ 2023', '2018 ~ 2024', '2014 ~ 2022',
       '2018 ~ 2023', '2016 ~ 2023', '2013 ~ 2023', '2011 ~ 2023',
       '2009 ~ 2022', '2005 ~ 2021', '2011 ~ 2021', '2015 ~ 2022',
       '2017 ~ 2024', '2010 ~ 2024', '2012 ~ 2021', '2019 ~ 2024',
       '2015 ~ 2024', '2017 ~ 2025', '2020 ~ 2025', '2019 ~ 2023',
       '2008 ~ 2023', '2015 ~ 2021', '2020 ~ 2022', '2012 ~ 2022',
       '2016 ~ 2025', '2013 ~ 2022', '2011 ~ 2022', '2012 ~ 2024',
       '2016 ~ 2021', '2012 ~ 2023', '2008 ~ 2022', '2019 ~ 2022',
       '2017 ~ 2021', '2013 ~ 2024', '2020 ~ 2024', '2010 ~ 2022',
       '2020 ~ 2021', '2011 ~ 2024', '2020 ~ 2023', '2014 ~ 2024',
       '2013 ~ 2026', '2016 ~ 2022', '2010 ~ 2021', '2013 ~ 2021',
       '2019 ~ 2025', '2018 ~ 2025', '2016 ~ 2024', '2018 ~ 2021',
       '2009 ~ 2024', '2007 ~ 2022', 'Jun 30, 2021 On Loan',
       '2009 ~ 2021', '2019 ~ 2021', '2019 ~ 2026', 'Free', '2012 ~ 

In [32]:
for index,row in fifa21.iterrows():
    if 'On Loan' in row['Contract'] or 'Free' in row['Contract']:
        print(row['Contract'])

Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Free
Free
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Free
Free
Free
Free
Free
Free
Free
Free
Free
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Free
Free
Free
Free
Jun 30, 2021 On Loan
Dec 31, 2020 On Loan
Jun 30, 2021 On Loan
Free
Jun 30, 2021 On Loan
Free
Free
Free
Free
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Free
Jun 30, 2021 On Loan
Free
Jun 30, 2021 On Loan
Jan 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Free
Dec 31, 2020 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Free
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Free
Jun 30, 2021 On Loan
Free
Free
Free

Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Dec 31, 2020 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Free
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Dec 31, 2020 On Loan
Dec 31, 2020 On Loan
May 31, 2021 On Loan
Jun 30, 2021 On Loan
Nov 27, 2021 On Loan
Free
Jun 30, 2021 On Loan
Free
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Dec 31, 2020 On Loan
Dec 31, 2020 On Loan
May 31, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Free
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Free
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2022 On Loan
Jun 30, 2021 On Loan
Free
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Dec 

Dec 31, 2020 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Nov 30, 2020 On Loan
Dec 31, 2020 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Free
Free
Jun 30, 2021 On Loan
Free
Free
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Nov 30, 2020 On Loan
Jun 30, 2021 On Loan
Aug 1, 2021 On Loan
Jun 30, 2021 On Loan
Free
Jun 30, 2021 On Loan
Nov 30, 2020 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Free
Dec 31, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Dec 31, 2020 On Loan
Jan 1, 2021 On Loan
Jun 30, 2021 On Loan
Free
Free
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Nov 30, 2020 On Loan
Dec 31, 2020 On Loan
Jun 30, 2021 On Loan
Jan 4, 2021 On Loan
Jun 30, 2021 On Loan
Nov 30, 2020 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Dec 31, 2021 On Loan
Free
Jun 30, 2021 On Loan
Dec 31, 2020 On Loan
Jun 30, 2021 

In [33]:
# lets segrigate contrac column into start_date,end_date,contract length
def extract_contract_info(contract): 
    if (contract=='Free') or 'On Loan' in contract:
        start_date=np.nan
        end_date=np.nan
        contract_length=0
    else:
        start_date, end_date=contract.split(' ~ ')
        start_year= int(start_date[:4])
        end_year= int(end_date[:4])    
        contract_length=end_year - start_year
    return start_date, end_date, contract_length

# apply above function to contract column and create new columns
new_cols=['Contract Start','Contract End','Contract Length(years)'] # new columns to be inserted in dataset
new_data=fifa21['Contract'].apply(lambda x: pd.Series(extract_contract_info(x))) # converting data return from function into series
for i in range(len(new_cols)):
    fifa21.insert(loc=fifa21.columns.get_loc('Contract')+1+i,column=new_cols[i], value=new_data[i])
    
    

In [34]:
fifa21.sample(4)

ID        Name         LongName  \
993    225126   E. Skhiri    Ellyes Skhiri   
18463  253079  M. Sibyani   Meshal Sibyani   
11033  184843    B. Tozer        Ben Tozer   
10726  216823  V. Vermeij  Vincent Vermeij   

                                               photoUrl  \
993    https://cdn.sofifa.com/players/225/126/21_60.png   
18463  https://cdn.sofifa.com/players/253/079/21_60.png   
11033  https://cdn.sofifa.com/players/184/843/21_60.png   
10726  https://cdn.sofifa.com/players/216/823/21_60.png   

                                               playerUrl   Nationality  Age  \
993    http://sofifa.com/player/225126/ellyes-skhiri/...       Tunisia   25   
18463  http://sofifa.com/player/253079/meshal-sibyani...  Saudi Arabia   19   
11033  http://sofifa.com/player/184843/ben-tozer/210006/       England   30   
10726  http://sofifa.com/player/216823/vincent-vermei...   Netherlands   25   

       ↓OVA  POT     Contract Contract Start Contract End  \
993      77   80  2019 ~ 2023           2019         2023   
18463    52   72  2019 ~ 2024           2019         2024   
11033    64   64  2018 ~ 2022           2018         2022   
10726    65   68  2019 ~ 2021           2019         2021   

       Contract Length(years) Positions Height Weight Preferred Foot  BOV  \
993                       4.0   CDM, CM  185cm   73kg          Right   78   
18463                     5.0       CDM  177cm   84kg           Left   57   
11033                     4.0        CB  185cm   81kg          Right   64   
10726                     2.0        ST  196cm   88kg          Right   67   

      Best Position     Joined Loan Date End   Value  Wage Release Clause  \
993             CDM  29-Jul-19           NaN  €12.5M  €25K         €18.8M   
18463            CB  23-Aug-19           NaN   €210K   €1K          €265K   
11033            CB   1-Jul-18           NaN   €475K   €3K          €656K   
10726            ST   1-Jul-19           NaN   €950K   €1K          €1.1M   

       Attacking  Crossing  Finishing  Heading Accuracy  Short Passing  \
993          343        71         62                73             77   
18463        171        32         18                50             48   
11033        268        57         38                62             58   
10726        315        49         67                82             59   

       Volleys  Skill  Dribbling  Curve  FK Accuracy  Long Passing  \
993         60    350         74     72           55            74   
18463       23    167         35     23           28            42   
11033       53    224         44     43           25            61   
10726       58    227         57     35           30            49   

       Ball Control  Movement  Acceleration  Sprint Speed  Agility  Reactions  \
993              75       326            62            55       74         71   
18463            39       267            61            59       37         47   
11033            51       295            55            54       57         61   
10726            56       248            46            53       43         60   

       Balance  Power  Shot Power  Jumping  Stamina  Strength  Long Shots  \
993         64    386          78       76       84        69          79   
18463       63    263          36       66       66        78          17   
11033       68    356          68       61       90        83          54   
10726       46    342          69       67       66        85          55   

       Mentality  Aggression  Interceptions  Positioning  Vision  Penalties  \
993          335          69             85           56      67         58   
18463        202          57             55           23      36         31   
11033        268          66             61           43      40         58   
10726        245          33             24           67      59         62   

       Composure  Defending  Marking  Standing Tackle  Sliding Tackle  \
993           69        227

In [35]:
def categorize_contract_status(contract):
    if contract=="Free":
        return 'Free'
    elif 'On Loan' in contract:
        return 'On Loan'
    else:
        return 'Contact'

fifa21.insert(fifa21.columns.get_loc('Contract Length(years)')+1, 'Contract Status', fifa21['Contract'].apply(categorize_contract_status))
fifa21.sample(6)

ID           Name                LongName  \
11343  256125  Leandro Silva  Leandro da Silva Alves   
16306  253009     A. Cáceres           Ariel Cáceres   
8145   224185     C. Leemans           Clint Leemans   
5653   228205     D. Cardoso          Daniel Cardoso   
8011   213147       J. Allen             Jamie Allen   
13477  180352        R. Finn              Ronan Finn   

                                               photoUrl  \
11343  https://cdn.sofifa.com/players/256/125/21_60.png   
16306  https://cdn.sofifa.com/players/253/009/21_60.png   
8145   https://cdn.sofifa.com/players/224/185/21_60.png   
5653   https://cdn.sofifa.com/players/228/205/21_60.png   
8011   https://cdn.sofifa.com/players/213/147/21_60.png   
13477  https://cdn.sofifa.com/players/180/352/21_60.png   

                                               playerUrl          Nationality  \
11343  http://sofifa.com/player/256125/leandro-da-sil...               Brazil   
16306  http://sofifa.com/player/253009/ariel-caceres/...                Chile   
8145   http://sofifa.com/player/224185/clint-leemans/...          Netherlands   
5653   http://sofifa.com/player/228205/daniel-cardoso...         South Africa   
8011   http://sofifa.com/player/213147/jamie-allen/21...              England   
13477  http://sofifa.com/player/180352/ronan-finn/210...  Republic of Ireland   

       Age  ↓OVA  POT     Contract Contract Start Contract End  \
11343   21    64   74  2018 ~ 2024           2018         2024   
16306   20    58   73  2019 ~ 2024           2019         2024   
8145    24    67   72  2018 ~ 2021           2018         2021   
5653    31    69   69  2015 ~ 2022           2015         2022   
8011    25    67   71  2019 ~ 2022           2019         2022   
13477   32    62   62  2016 ~ 2021           2016         2021   

       Contract Length(years) Contract Status Positions Height Weight  \
11343                     6.0         Contact    LW, RW  174cm   67kg   
16306                     5.0         Contact        RM  181cm   72kg   
8145                      3.0         Contact   CM, CDM  189cm   79kg   
5653                      7.0         Contact        CB  184cm   78kg   
8011                      3.0         Contact   CM, CAM  170cm   72kg   
13477                     5.0         Contact  RWB, CAM  185cm   71kg   

      Preferred Foot  BOV Best Position     Joined Loan Date End  Value  Wage  \
11343           Left   65           CAM   1-Jul-18           NaN  €1.3M   €2K   
16306          Right   59            RM  25-May-19           NaN  €500K  €500   
8145            Left   69            CM  13-Jul-18           NaN  €1.5M   €3K   
5653            Left   69            CB  23-Jun-15           NaN  €950K  €500   
8011           Right   69            CM  28-Jun-19           NaN  €1.4M  €14K   
13477          Right   62           RWB  20-Dec-16           NaN  €275K  €700   

      Release Clause  Attacking  Crossing  Finishing  Heading Accuracy  \
11343          €1.7M        286        65         58                44   
16306          €543K        247        52         53                39   
8145           €1.5M        326        75         62                56   
5653           €1.7M        231        40         29                68   
8011           €1.9M        291        63         57                55   
13477          €295K        284        57         55                55   

       Short Passing  Volleys  Skill  Dribbling  Curve  FK Accuracy  \
11343             60       59    317         69     70           60   
16306             55       48    252         66     42           39   
8145              69       64    357         62     74           78   
5653              53       41    237         53     32           31   
8011              71       45    308         64     57           53   
13477             63       54    298         64     53           57   

       Long Passing  Ball Control  Movement  Acceleration  Sprint Speed  \
1

In [36]:
fifa21.sample(20)

ID               Name               LongName  \
17042  256701           D. Glass           Declan Glass   
17098  240945        G. McGregor      Giovanni McGregor   
17304  254807            K. Baah            Kwadwo Baah   
3283   203590          F. Hübner         Florian Hübner   
8575   171033        M. Andersen        Mikkel Andersen   
3271   189514           H. Afful         Harrison Afful   
77     212188          T. Werner            Timo Werner   
10486  259012     T. Dzvukamanja   Terrence Dzvukamanja   
784    211899   F. Niederlechner  Florian Niederlechner   
16831  255564  J. Shcherbakovski     Jan Shcherbakovski   
2257   216700            M. Meza       Maximiliano Meza   
5773   254062           K. Minda            Kevin Minda   
15967  257714      S. Augustijns       Sebbe Augustijns   
11589  241586        Iñigo Muñoz     Iñigo Muñoz Cuevas   
713    235805          F. Chiesa        Federico Chiesa   
12728  200633        R. McDonald           Rod McDonald   
7711   203606          J. Skalák            Jiří Skalák   
4949   239732       S. Żurkowski       Szymon Żurkowski   
2302   212715        S. Palacios     Sebastián Palacios   
9      192448      M. ter Stegen  Marc-André ter Stegen   

                                               photoUrl  \
17042  https://cdn.sofifa.com/players/256/701/21_60.png   
17098  https://cdn.sofifa.com/players/240/945/21_60.png   
17304  https://cdn.sofifa.com/players/254/807/21_60.png   
3283   https://cdn.sofifa.com/players/203/590/21_60.png   
8575   https://cdn.sofifa.com/players/171/033/21_60.png   
3271   https://cdn.sofifa.com/players/189/514/21_60.png   
77     https://cdn.sofifa.com/players/212/188/21_60.png   
10486  https://cdn.sofifa.com/players/259/012/21_60.png   
784    https://cdn.sofifa.com/players/211/899/21_60.png   
16831  https://cdn.sofifa.com/players/255/564/21_60.png   
2257   https://cdn.sofifa.com/players/216/700/21_60.png   
5773   https://cdn.sofifa.com/players/254/062/21_60.png   
15967  https://cdn.sofifa.com/players/257/714/21_60.png   
11589  https://cdn.sofifa.com/players/241/586/21_60.png   
713    https://cdn.sofifa.com/players/235/805/21_60.png   
12728  https://cdn.sofifa.com/players/200/633/21_60.png   
7711   https://cdn.sofifa.com/players/203/606/21_60.png   
4949   https://cdn.sofifa.com/players/239/732/21_60.png   
2302   https://cdn.sofifa.com/players/212/715/21_60.png   
9      https://cdn.sofifa.com/players/192/448/21_60.png   

                                               playerUrl     Nationality  Age  \
17042  http://sofifa.com/player/256701/declan-glass/2...        Scotland   20   
17098  http://sofifa.com/player/240945/giovanni-mcgre...         England   21   
17304  http://sofifa.com/player/254807/kwadwo-baah/21...         England   17   
3283   http://sofifa.com/player/203590/florian-hubner...         Germany   29   
8575   http://sofifa.com/player/171033/mikkel-anderse...         Denmark   31   
3271   http://sofifa.com/player/189514/harrison-afful...           Ghana   34   
77     http://sofifa.com/player/212188/timo-werner/21...         Germany   24   
10486  http://sofifa.com/player/259012/terrence-dzvuk...        Zimbabwe   26   
784    http://sofifa.com/player/211899/florian-nieder...         Germany   29   
16831  http://sofifa.com/player/255564/jan-shcherbako...         Belarus   19   
2257   http://sofifa.com/player/216700/maximiliano-me...       Argentina   27   
5773   http://sofifa.com/player/254062/kevin-minda/21...         Ecuador   21   
15967  http://sofifa.com/player/257714/sebbe-augustij...         Belgium   20   
11589  http://sofifa.com/player/241586/inigo-munoz-cu...           Spain   23   
713    http://sofifa.com/player/235805/federico-chies...           Italy   22   
12728  http://sofifa.com/player/200633/rod-mcdonald/2...         England   28   
7711   http://sofifa.com/player/203606/jiri-skalak/21...  Czech Republic   28   
4949   http://sofifa.com/player/239732/szymon-zurkows...          Poland 

In [37]:
fifa21.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 80 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   ID                      18979 non-null  int64  
 1   Name                    18979 non-null  object 
 2   LongName                18979 non-null  object 
 3   photoUrl                18979 non-null  object 
 4   playerUrl               18979 non-null  object 
 5   Nationality             18979 non-null  object 
 6   Age                     18979 non-null  int64  
 7   ↓OVA                    18979 non-null  int64  
 8   POT                     18979 non-null  int64  
 9   Contract                18979 non-null  object 
 10  Contract Start          17729 non-null  object 
 11  Contract End            17729 non-null  object 
 12  Contract Length(years)  18979 non-null  float64
 13  Contract Status         18979 non-null  object 
 14  Positions               18979 non-null

### 12. Positions

Player's preferred position on the field

### 13. Height

In [38]:
fifa21['Height'].dtype

dtype('O')

In [39]:
fifa21['Height'].unique()

array(['170cm', '187cm', '188cm', '181cm', '175cm', '184cm', '191cm',
       '178cm', '193cm', '185cm', '199cm', '173cm', '168cm', '176cm',
       '177cm', '183cm', '180cm', '189cm', '179cm', '195cm', '172cm',
       '182cm', '186cm', '192cm', '165cm', '194cm', '167cm', '196cm',
       '163cm', '190cm', '174cm', '169cm', '171cm', '197cm', '200cm',
       '166cm', '6\'2"', '164cm', '198cm', '6\'3"', '6\'5"', '5\'11"',
       '6\'4"', '6\'1"', '6\'0"', '5\'10"', '5\'9"', '5\'6"', '5\'7"',
       '5\'4"', '201cm', '158cm', '162cm', '161cm', '160cm', '203cm',
       '157cm', '156cm', '202cm', '159cm', '206cm', '155cm'], dtype=object)

In [40]:
# above output shows that some values are in cm and some in inches and feet so we need to convert all to same format so that column type can be set to integers
def convert_units(height):
    if 'cm' in height:
        return int(height.strip("cm"))
    else:
        feet, inches= height.split("'")
        total_inches=int(feet)*12+int(inches.strip(' " '))
        return round(total_inches*2.54)

fifa21['Height']=fifa21['Height'].apply(convert_units)
fifa21['Height'].unique()

array([170, 187, 188, 181, 175, 184, 191, 178, 193, 185, 199, 173, 168,
       176, 177, 183, 180, 189, 179, 195, 172, 182, 186, 192, 165, 194,
       167, 196, 163, 190, 174, 169, 171, 197, 200, 166, 164, 198, 201,
       158, 162, 161, 160, 203, 157, 156, 202, 159, 206, 155], dtype=int64)

In [41]:
fifa21=fifa21.rename(columns={'Height': "Height(cm)"})
fifa21.sample(3)

ID        Name       LongName  \
6920  216477  T. Nedelev  Todor Nedelev   
2033  207650   E. Krafth    Emil Krafth   
7814  238958   R. Harper  Rekeem Harper   

                                              photoUrl  \
6920  https://cdn.sofifa.com/players/216/477/21_60.png   
2033  https://cdn.sofifa.com/players/207/650/21_60.png   
7814  https://cdn.sofifa.com/players/238/958/21_60.png   

                                              playerUrl Nationality  Age  \
6920  http://sofifa.com/player/216477/todor-nedelev/...    Bulgaria   27   
2033  http://sofifa.com/player/207650/emil-krafth/21...      Sweden   25   
7814  http://sofifa.com/player/238958/rekeem-harper/...     England   20   

      ↓OVA  POT     Contract Contract Start Contract End  \
6920    68   68         Free            NaN          NaN   
2033    74   77  2019 ~ 2023           2019         2023   
7814    67   79  2017 ~ 2022           2017         2022   

      Contract Length(years) Contract Status Positions  Height(cm) Weight  \
6920                     0.0            Free   RM, CAM         177   72kg   
2033                     4.0         Contact    RB, CB         181   72kg   
7814                     5.0         Contact   CM, CDM         188   76kg   

     Preferred Foot  BOV Best Position    Joined Loan Date End  Value  Wage  \
6920           Left   68            RM  1-Jul-17           NaN     €0    €0   
2033          Right   74            RB  8-Aug-19           NaN    €5M  €29K   
7814          Right   69            CM  1-Apr-17           NaN  €2.4M  €18K   

     Release Clause  Attacking  Crossing  Finishing  Heading Accuracy  \
6920             €0        282        66         67                23   
2033         €11.9M        289        68         41                64   
7814          €2.9M        279        56         42                60   

      Short Passing  Volleys  Skill  Dribbling  Curve  FK Accuracy  \
6920             67       59    337         68     69           70   
2033             70       46    325         68     70           54   
7814             71       50    291         67     42           44   

      Long Passing  Ball Control  Movement  Acceleration  Sprint Speed  \
6920            63            67       342            71            68   
2033            62            71       353            64            74   
7814            69            69       347            69            67   

      Agility  Reactions  Balance  Power  Shot Power  Jumping  Stamina  \
6920       73         64       66    305          72       49       65   
2033       72         74       69    338          70       68       75   
7814       68         68       75    347          69       71       76   

      Strength  Long Shots  Mentality  Aggression  Interceptions  Positioning  \
6920        50          69        283          50             28           69   
2033        67          58        310          72             72           52   
7814        71          60        316          71             55           64   

      Vision  Penalties  Composure  Defending  Marking  Standing Tackle  \
6920      65         71         53         99       34               34   
2033      60         54         72        221       73               75   
7814      70         56         76        183       64               60   

      Sliding Tackle  Goalkeeping  GK Diving  GK Handling  GK Kicking  \
6920              31           44         10            9           8   
2033              73           57          8           13          15   
7814              59           60         13           10          11   

      GK Positioning  GK Reflexes  Total Stats  Base Stats  W/F  SM     A/W  \
6920               7           10         1692         356  3 ★  3★  Medium   
2033              14            7         1893         401  3 ★  3★    High   
7814              13           13         1823         386  3 ★  3★  Medium   

         D/W   IR  PAC  SHO 

### 14. Weight

In [42]:
# unique method will give units in vlaues and data type  of the column
fifa21['Weight'].unique()

array(['72kg', '83kg', '87kg', '70kg', '68kg', '80kg', '71kg', '91kg',
       '73kg', '85kg', '92kg', '69kg', '84kg', '96kg', '81kg', '82kg',
       '75kg', '86kg', '89kg', '74kg', '76kg', '64kg', '78kg', '90kg',
       '66kg', '60kg', '94kg', '79kg', '67kg', '65kg', '59kg', '61kg',
       '93kg', '88kg', '97kg', '77kg', '62kg', '63kg', '95kg', '100kg',
       '58kg', '183lbs', '179lbs', '172lbs', '196lbs', '176lbs', '185lbs',
       '170lbs', '203lbs', '168lbs', '161lbs', '146lbs', '130lbs',
       '190lbs', '174lbs', '148lbs', '165lbs', '159lbs', '192lbs',
       '181lbs', '139lbs', '154lbs', '157lbs', '163lbs', '98kg', '103kg',
       '99kg', '102kg', '56kg', '101kg', '57kg', '55kg', '104kg', '107kg',
       '110kg', '53kg', '50kg', '54kg', '52kg'], dtype=object)

In [43]:
# above output shows that some values are in kg and some in lbs so we need to convert all to same format so that column type can be set to integers
def convert_weight(weight):
    if 'kg' in weight:
        return int(weight.strip("kg"))
    else:
        
        pounds=int(weight.strip('lbs'))
        return round(pounds/2.205)
#apply function to weight column
fifa21['Weight']=fifa21['Weight'].apply(convert_weight)
fifa21['Weight'].unique()

array([ 72,  83,  87,  70,  68,  80,  71,  91,  73,  85,  92,  69,  84,
        96,  81,  82,  75,  86,  89,  74,  76,  64,  78,  90,  66,  60,
        94,  79,  67,  65,  59,  61,  93,  88,  97,  77,  62,  63,  95,
       100,  58,  98, 103,  99, 102,  56, 101,  57,  55, 104, 107, 110,
        53,  50,  54,  52], dtype=int64)

In [44]:
fifa21=fifa21.rename(columns={'Weight': "Weight(kg)"})
fifa21.sample(3)

ID            Name                        LongName  \
16830  256075       L. Rangel                     Luis Rangel   
1908   235997    Fran Beltrán  Francisco José Beltrán Peinado   
985    203106  L. Bittencourt            Leonardo Bittencourt   

                                               photoUrl  \
16830  https://cdn.sofifa.com/players/256/075/21_60.png   
1908   https://cdn.sofifa.com/players/235/997/21_60.png   
985    https://cdn.sofifa.com/players/203/106/21_60.png   

                                               playerUrl Nationality  Age  \
16830  http://sofifa.com/player/256075/luis-rangel/21...   Venezuela   18   
1908   http://sofifa.com/player/235997/francisco-jose...       Spain   21   
985    http://sofifa.com/player/203106/leonardo-bitte...     Germany   26   

       ↓OVA  POT     Contract Contract Start Contract End  \
16830    57   68  2020 ~ 2024           2020         2024   
1908     75   83  2018 ~ 2023           2018         2023   
985      77   78  2020 ~ 2024           2020         2024   

       Contract Length(years) Contract Status     Positions  Height(cm)  \
16830                     4.0         Contact            CB         190   
1908                      5.0         Contact  CM, CDM, CAM         170   
985                       4.0         Contact    RM, LM, CM         170   

       Weight(kg) Preferred Foot  BOV Best Position    Joined Loan Date End  \
16830          68          Right   59            CB  1-Jan-20           NaN   
1908           66          Right   78           CDM  1-Aug-18           NaN   
985            62          Right   77            RM  1-Jul-20           NaN   

        Value  Wage Release Clause  Attacking  Crossing  Finishing  \
16830   €325K  €500          €353K        201        29         29   
1908   €12.5M  €16K           €23M        319        72         53   
985    €12.5M  €29K         €19.7M        333        73         68   

       Heading Accuracy  Short Passing  Volleys  Skill  Dribbling  Curve  \
16830                56             51       36    184         33     35   
1908                 60             79       55    341         79     54   
985                  46             77       69    384         86     77   

       FK Accuracy  Long Passing  Ball Control  Movement  Acceleration  \
16830           28            31            57       283            61   
1908            55            77            76       360            66   
985             70            72            79       412            85   

       Sprint Speed  Agility  Reactions  Balance  Power  Shot Power  Jumping  \
16830            57       55         56       54    265          35       69   
1908             65       77         75       77    313          61       58   
985              74       90         74       89    325          70       65   

       Stamina  Strength  Long Shots  Mentality  Aggression  Interceptions  \
16830       61        66          34        208          60             55   
1908        70        64          60        333          68             76   
985         76        46          68        330          74             55   

       Positioning  Vision  Penalties  Composure  Defending  Marking  \
16830           33      32         28         42        164       51   
1908            63      77         49         66        231       78   
985             68      72         61         72        172       58   

       Standing Tackle  Sliding Tackle  Goalkeeping  GK Diving  GK Handling  \
16830               59              54           50          9           13   
1908                77              76           55         14           11   
985                 57              57           62         15           11   

       GK Kicking  GK Positioning  GK Reflexes  Total Stats  Base Stats  W/F  \
16830          12               8            8         1355         293  3 ★   
1908            8              13            9         195

### 15. Preferred Foot

Player's preferred foot - Left or Right

### 16. BOV

Best Overall Rating of the Player in a specific position

### 17. Best Position

Player's best position on the field

### 18. Joined

Date when the player joined the current club

In [45]:
fifa21['Joined'].unique()

array(['1-Jul-04', '10-Jul-18', '16-Jul-14', ..., '22-Sep-18',
       '28-Feb-15', '6-Mar-18'], dtype=object)

### 19. Loan Date End

Date when the player's loan ends (if On Loan)

In [46]:
# this dae value shas entries for those row where contract is on loan
fifa21['Loan Date End'].unique()

array([nan, '30-Jun-21', '31-Dec-20', '30-Jan-21', '30-Jun-22',
       '31-May-21', '5-Jul-21', '31-Dec-21', '1-Jul-21', '1-Jan-21',
       '31-Aug-21', '31-Jan-21', '30-Dec-21', '23-Jun-21', '3-Jan-21',
       '27-Nov-21', '17-Jan-21', '30-Jun-23', '31-Jul-21', '22-Nov-20',
       '31-May-22', '30-Dec-20', '4-Jan-21', '30-Nov-20', '1-Aug-21'],
      dtype=object)

In [47]:
on_loan=fifa21[fifa21['Contract Status']=='On Loan']
on_loan[['Contract', 'Contract Status', 'Loan Date End']]

Contract Contract Status Loan Date End
205    Jun 30, 2021 On Loan         On Loan     30-Jun-21
248    Jun 30, 2021 On Loan         On Loan     30-Jun-21
254    Jun 30, 2021 On Loan         On Loan     30-Jun-21
302    Jun 30, 2021 On Loan         On Loan     30-Jun-21
306    Jun 30, 2021 On Loan         On Loan     30-Jun-21
...                     ...             ...           ...
18472  Aug 31, 2021 On Loan         On Loan     31-Aug-21
18571  Jun 30, 2021 On Loan         On Loan     30-Jun-21
18600  Dec 31, 2020 On Loan         On Loan     31-Dec-20
18622  Dec 31, 2020 On Loan         On Loan     31-Dec-20
18680  Dec 31, 2020 On Loan         On Loan     31-Dec-20

[1013 rows x 3 columns]

### 20. Value

Estimated market value of the player.

In [48]:
fifa21['Value'].unique()

array(['€103.5M', '€63M', '€120M', '€129M', '€132M', '€111M', '€120.5M',
       '€102M', '€185.5M', '€110M', '€113M', '€90.5M', '€82M', '€17.5M',
       '€83.5M', '€33.5M', '€114.5M', '€78M', '€103M', '€109M', '€92M',
       '€10M', '€76.5M', '€89.5M', '€87.5M', '€79.5M', '€124M', '€114M',
       '€95M', '€92.5M', '€105.5M', '€88.5M', '€85M', '€81.5M', '€26M',
       '€21M', '€56M', '€67.5M', '€53M', '€36.5M', '€51M', '€65.5M',
       '€46.5M', '€61.5M', '€72.5M', '€77.5M', '€43.5M', '€32.5M', '€36M',
       '€32M', '€54M', '€49.5M', '€57M', '€66.5M', '€74.5M', '€71.5M',
       '€121M', '€99M', '€67M', '€86.5M', '€93.5M', '€70M', '€62M',
       '€66M', '€58M', '€44M', '€81M', '€37M', '€14.5M', '€46M', '€47.5M',
       '€52.5M', '€54.5M', '€34.5M', '€57.5M', '€51.5M', '€44.5M', '€55M',
       '€48M', '€60.5M', '€63.5M', '€61M', '€29M', '€58.5M', '€55.5M',
       '€42M', '€40.5M', '€43M', '€45.5M', '€34M', '€26.5M', '€42.5M',
       '€35.5M', '€45M', '€41.5M', '€40M', '€11M', '€13.5M', '

### 21. Wage

Weekly wage of the player.

In [49]:
fifa21['Wage'].unique()

array(['€560K', '€220K', '€125K', '€370K', '€270K', '€240K', '€250K',
       '€160K', '€260K', '€210K', '€310K', '€130K', '€350K', '€300K',
       '€190K', '€145K', '€195K', '€100K', '€140K', '€290K', '€82K',
       '€110K', '€230K', '€155K', '€200K', '€165K', '€95K', '€170K',
       '€105K', '€115K', '€150K', '€135K', '€55K', '€58K', '€81K', '€34K',
       '€120K', '€59K', '€90K', '€65K', '€56K', '€71K', '€18K', '€75K',
       '€47K', '€20K', '€84K', '€86K', '€74K', '€78K', '€27K', '€68K',
       '€85K', '€25K', '€46K', '€83K', '€54K', '€79K', '€175K', '€43K',
       '€49K', '€45K', '€38K', '€41K', '€39K', '€23K', '€51K', '€50K',
       '€87K', '€30K', '€14K', '€69K', '€31K', '€64K', '€53K', '€35K',
       '€21K', '€28K', '€17K', '€33K', '€70K', '€32K', '€89K', '€26K',
       '€40K', '€76K', '€72K', '€48K', '€36K', '€29K', '€60K', '€16K',
       '€37K', '€24K', '€52K', '€0', '€62K', '€73K', '€63K', '€19K',
       '€1K', '€66K', '€80K', '€12K', '€2K', '€42K', '€13K', '€900',
       '€5

### 22. Release Clause

Release clause in the player's contract

In [50]:
fifa21['Release Clause'].unique()

array(['€138.4M', '€75.9M', '€159.4M', ..., '€59K', '€35K', '€64K'],
      dtype=object)

### 23. Attacking

Composite rating of the player's attacking ability.

In [51]:
fifa21['Attacking'].unique()

array([429, 437,  95, 407, 408, 423, 392, 114, 118, 316, 410, 349,  86,
       119, 426, 374, 411, 360, 328, 383, 405, 123, 420, 224, 388, 397,
       425, 373, 365, 371, 311, 396, 345, 399, 400,  78, 280, 330, 403,
       379, 380,  94, 394, 419, 339, 293, 344, 390,  84, 359, 372, 377,
       346, 389, 386, 308, 277, 382, 368, 402, 292, 298, 366, 352, 363,
       322, 361,  91, 364, 341, 385, 355, 305, 321, 262,  93, 375, 387,
       356, 253, 285, 391, 353, 367,  90, 295, 378, 256, 338, 331,  69,
       105,  85, 358, 343, 319, 271, 113, 350, 406, 340, 393, 247, 334,
       351, 342, 302, 329, 354,  98, 301, 115, 384, 208,  72, 376,  92,
       258, 362,  74, 417,  99, 263,  88, 279, 101, 395, 100,  81,  87,
        55, 310,  82, 117, 409, 318, 323, 248, 315, 381, 348, 327, 309,
       130, 283, 336, 369, 106, 252, 320, 290, 370, 126, 251, 108, 335,
       297, 284,  80,  75, 357, 270,  97, 306, 337,  73, 286, 325, 326,
       324, 333, 103, 259, 273, 313, 296,  61, 312, 347, 401, 30

### 24. Crossing

Player's ability to make accurate crosses.

In [52]:
fifa21['Crossing'].unique()

array([85, 84, 13, 94, 71, 79, 17, 78, 18, 53, 76, 58, 14, 15, 75, 66, 70,
       68, 91, 82, 20, 12, 30, 77, 88, 83, 93, 90, 87, 81, 73, 11, 54, 62,
       86, 80, 55, 42, 57, 65, 63, 64, 52, 40, 69, 47, 60,  9, 16, 44, 72,
       50, 56, 46, 89, 34, 45, 74, 49, 67, 24, 35, 36, 61, 19, 27, 25, 10,
       51, 38, 43, 59, 39, 48, 23,  8, 28, 92, 41, 29, 32, 22, 26, 37, 33,
       31, 21,  7,  6], dtype=int64)

### 25. Finishing

Player's ability to score goals

In [53]:
fifa21['Finishing'].unique()

array([95, 11, 82, 87, 94, 91, 13, 14, 52, 90, 64, 88, 65, 85, 66, 84, 10,
       22, 76, 81, 56, 79, 57, 45, 77, 63, 86, 80, 15, 33, 67, 12, 72, 92,
       93, 51, 46, 60, 75, 55, 73, 83, 50, 42, 39, 40,  9, 68, 48, 37, 70,
       78, 69,  8, 53, 89, 25, 62, 71, 74, 44, 26, 19, 32, 18, 61, 58, 30,
       54, 36, 29, 16, 38, 59, 27, 34, 47, 20, 31, 49, 43, 41, 28,  5,  7,
        6, 21, 17, 35, 23, 24,  4,  3], dtype=int64)

### 26. Heading Accuracy

Player's ability to win aerial duels.

In [54]:
fifa21['Heading Accuracy'].unique()

array([70, 90, 15, 55, 62, 85, 59, 19, 73, 11, 87, 84, 80, 13, 25, 91, 92,
       78, 46, 54, 72, 64, 14, 10, 61, 58, 83, 38, 69, 51, 67, 86, 75, 68,
       16, 81, 21, 79, 53, 65, 82, 12, 42, 48, 88, 66, 76, 74, 52, 23, 40,
       49, 60, 44, 20, 37, 71, 17, 45, 77, 50, 63, 43, 39, 57, 56, 47, 24,
       18, 31, 28, 35, 34, 41, 36, 93,  7, 30, 89,  8, 26, 33, 27, 32, 22,
       29,  9,  5,  6], dtype=int64)

### 27. Short Passing

Player's ability to make short passes accurately.

In [55]:
fifa21['Short Passing'].unique()

array([91, 82, 43, 94, 87, 84, 45, 83, 61, 79, 85, 33, 55, 86, 57, 81, 42,
       74, 93, 88, 30, 65, 89, 77, 32, 50, 80, 78, 90, 69, 40, 92, 75, 73,
       34, 76, 35, 70, 37, 23, 44, 38, 48, 26, 60, 25, 46, 28, 24, 36, 51,
       17, 18, 39, 71, 67, 27, 72, 66, 20, 31, 68, 29, 11, 64, 62, 41, 63,
       19, 54, 16, 22, 49, 59, 56, 14, 58, 15, 21, 52, 53, 12, 47, 13,  8,
        7], dtype=int64)

### 28. Volleys

Player's ability to take volleys

In [56]:
fifa21['Volleys'].unique()

array([88, 86, 13, 82, 87, 89, 79, 20, 83, 14, 45, 75, 63, 12, 11, 69, 67,
       56, 18, 85, 62, 70, 32, 40, 47, 81, 44, 84, 78, 76, 90, 49, 42, 64,
       57, 60,  8, 72, 71, 59, 74, 80, 73, 37, 31, 38, 61, 10, 77, 68, 58,
       66, 30, 33, 65, 27, 51, 15, 16, 50, 43, 35, 24, 17, 34, 28,  9, 39,
       52, 46, 22, 19, 53, 55, 48, 54, 23,  5, 41, 25, 21, 36, 26, 29,  6,
        7,  4,  3], dtype=int64)

### 29. Skill

Composite rating of the player's technical abilities.

In [57]:
fifa21['Skill'].unique()

array([470, 414, 109, 441, 448, 407, 406, 138, 394, 144, 363, 391, 369,
       110, 160, 404, 381, 397, 387, 336, 400, 436, 157, 395, 100, 262,
       427, 432, 429, 380, 426, 411, 358, 351, 433, 365, 403,  98, 276,
       386, 383,  99, 413, 115, 341, 375, 143, 359, 309, 435, 330, 325,
       355,  96, 420, 412, 388, 319, 269, 399, 106, 402, 425, 297, 312,
       418, 372, 352, 439, 409, 349, 116, 371, 428, 104, 345, 430, 295,
       405, 440, 422, 252, 401, 417, 396, 233, 377, 251, 382, 368,  84,
       356, 342, 410, 271, 350,  83, 126, 103, 370, 362, 343, 328, 344,
       415, 378, 275, 416, 119, 127, 373, 384,  77, 393, 348, 317, 408,
       376, 300, 220,  89, 107, 334,  72, 390, 419, 305, 289, 398, 281,
       354, 102, 339, 385, 139, 292,  97, 421,  91, 105,  73, 335, 101,
       340, 337, 306, 113, 122, 123, 302, 364, 250, 347, 333, 323, 389,
       361, 322,  86, 367, 258, 392,  92,  90, 310, 331, 338, 121, 260,
        82, 245, 324, 346, 379, 299, 284, 320, 283, 108, 278, 28

### 30. Dribbling

Player's ability to dribble past defenders.

In [58]:
fifa21['Dribbling'].unique()

array([96, 88, 12, 95, 85, 90, 27, 92, 21, 70, 91, 69, 13, 30, 87, 65, 79,
       83, 23, 80, 18, 93, 77, 63, 76, 16, 59, 81, 11, 84, 10, 75, 78, 55,
       15, 86, 66, 67, 28, 57, 64, 82, 62, 19, 53, 72, 50, 26, 43, 89, 73,
       20, 14, 68, 71, 74, 22, 54, 56, 61,  9, 24, 60, 25,  8, 17, 47, 58,
       46, 42, 51, 52, 49, 44, 35, 48, 39, 29, 40, 45, 34, 31, 33, 38, 41,
       32,  7, 37, 36,  5,  6], dtype=int64)

### 31. Curve

Player's ability to curve the ball.

In [59]:
fifa21['Curve'].unique()

array([93, 81, 13, 85, 88, 79, 83, 19, 18, 60, 76, 63, 14, 74, 77, 49, 15,
       80, 12, 28, 86, 84, 82, 61, 71, 11, 66, 16, 89, 70, 21, 46, 78, 67,
       58, 65, 48, 34, 90, 59, 55, 87, 62,  9, 56, 36, 30, 32, 73, 69, 68,
       75, 45, 10, 72, 64, 41, 23, 47, 20, 51, 25, 44, 17, 54, 57, 53, 33,
       40, 50, 39, 35, 52, 42, 37, 43, 26, 31, 92, 91, 29, 94, 27, 38, 22,
       24,  8,  6,  7,  5,  4], dtype=int64)

### 32. FK Accuracy

Player's ability to take free kicks.

In [60]:
fifa21['FK Accuracy'].unique()

array([94, 76, 14, 83, 89, 85, 69, 18, 63, 12, 70, 64, 74, 20, 11, 73, 49,
       61, 88, 68, 28, 79, 84, 48, 67, 38, 87, 53, 65, 15, 31, 78, 82, 10,
       51, 59, 19, 47, 52, 57, 43, 13, 77, 54, 75, 86, 55, 30, 62, 32, 58,
       93,  8, 66, 71, 81, 92, 44, 17, 60, 40, 16, 72, 46, 35, 45, 29, 21,
       56, 80, 24, 22, 39, 42, 26, 41,  9, 37, 27, 50, 33, 25, 36, 91, 34,
       23,  7,  6, 90,  5], dtype=int64)

### 33. Long Passing

Player's ability to make long passes accurately.

In [61]:
fifa21['Long Passing'].unique()

array([91, 77, 40, 93, 81, 70, 75, 44, 63, 86, 71, 84, 35, 59, 73, 83, 64,
       69, 79, 82, 68, 89, 76, 80, 87, 37, 65, 36, 50, 53, 78, 47, 74, 48,
       31, 85, 24, 55, 90, 54, 62, 32, 49, 66, 67, 51, 28, 46, 52, 72, 56,
       41, 45, 22, 88, 61, 33, 12, 60, 17, 27, 29, 23, 38, 16, 58, 34, 25,
       39, 21, 30, 42, 43, 57, 20, 26, 18, 19, 13, 15, 11, 14,  9, 10,  5,
        8], dtype=int64)

### 34. Ball Control

Player's ability to control the ball.

In [62]:
fifa21['Ball Control'].unique()

array([96, 92, 30, 95, 88, 89, 90, 77, 79, 23, 46, 83, 80, 85, 94, 40, 84,
       16, 74, 91, 87, 82, 78, 19, 61, 22, 34, 38, 81, 25, 86, 76, 69, 28,
       93, 75, 35, 60, 63, 73, 18, 71, 15, 21, 72, 14, 65, 20, 24, 27, 70,
       33, 17, 62, 64,  9, 68, 67, 32, 26, 66, 52, 11, 57, 58, 29, 12, 37,
       10, 36, 13, 31, 55, 59, 39, 54, 56, 48, 44, 51, 50, 47, 49, 53,  5,
       42,  8, 45, 43, 41,  7], dtype=int64)

### 35. Movement

Composite rating of the player's movement abilities.

In [63]:
fifa21['Movement'].unique()

array([451, 431, 307, 398, 453, 407, 460, 268, 458, 254, 354, 343, 284,
       286, 388, 378, 424, 464, 420, 399, 437, 322, 367, 272, 328, 448,
       332, 425, 435, 391, 434, 400, 331, 349, 429, 416, 312, 326, 418,
       419, 417, 386, 321, 409, 374, 304, 403, 351, 401, 365, 414, 292,
       323, 299, 433, 350, 348, 413, 320, 281, 427, 353, 364, 410, 428,
       316, 381, 442, 375, 288, 395, 385, 251, 319, 444, 383, 298, 411,
       412, 415, 393, 397, 443, 423, 387, 422, 327, 390, 362, 352, 406,
       277, 361, 421, 396, 384, 450, 338, 363, 359, 287, 297, 430, 382,
       377, 380, 438, 449, 257, 371, 339, 341, 404, 345, 394, 295, 246,
       265, 258, 366, 294, 314, 266, 405, 218, 337, 267, 220, 376, 309,
       283, 426, 347, 244, 240, 291, 340, 250, 305, 290, 317, 334, 355,
       333, 389, 330, 318, 441, 402, 344, 335, 219, 264, 408, 274, 373,
       379, 256, 229, 392, 372, 360, 262, 346, 278, 248, 368, 279, 269,
       336, 342, 236, 370, 243, 315, 249, 227, 329, 239, 369, 22

In [64]:
fifa21.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 80 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   ID                      18979 non-null  int64  
 1   Name                    18979 non-null  object 
 2   LongName                18979 non-null  object 
 3   photoUrl                18979 non-null  object 
 4   playerUrl               18979 non-null  object 
 5   Nationality             18979 non-null  object 
 6   Age                     18979 non-null  int64  
 7   ↓OVA                    18979 non-null  int64  
 8   POT                     18979 non-null  int64  
 9   Contract                18979 non-null  object 
 10  Contract Start          17729 non-null  object 
 11  Contract End            17729 non-null  object 
 12  Contract Length(years)  18979 non-null  float64
 13  Contract Status         18979 non-null  object 
 14  Positions               18979 non-null

### 37. Sprint Speed

Player's top speed

### 38. Agility

Player's agility

### 39. Reactions

Player's reaction time

### 40. Balance

Player's balance

### 41. Power

Composite rating of player's physical abilities

### 42. Shot Power

Player's ability to shoot with power

### 43. Jumping

Player's ability to jump high

### 44. Stamina

Player's stamina.

### 45. Strength

Player's physical strength.

### 46. Long Shots

Player's ability to score from long range

### 47. Mentality

Composite rating of the player's mental abilities.

### 48. Aggression

Player's aggression on the field.

### 49. Interceptions

Player's ability to intercept passes.

### 50. Positioning

Player's ability to position themselves well on the field.

### 51. Vision

Players ability to see and execute passes.

### 52. Penalties

Player's ability to score penalties.

### 53. Composure

Player's composure under pressure.

### 54. Defending

Composite rating of the player's defensive abilities.

### 55. Marking

Player's ability to mark opposing players.

### 56. Standing Tackle

Player's ability to make standing tackles.

### 57. Sliding Tackle

Player's ability to make sliding tackles.

### 58. Goalkeeping

Composite rating of the player's goalkeeping abilities. Only for goalkeepers

### 59. GK Diving

Goalkeeper's ability to dive to make saves.

### 60. GK Handling

Goalkeeper's ability to handle the ball

### 61. GK Kicking

Goalkeeper's ability to kick the ball.

### 62. GK Positioning

Goalkeeper's ability to position themselves well.

### 63. GK Reflexes

Goalkeeper's reflexes

### 64. Total Stats

Total number of stats in the game

### 65. Base Stats

Number of stats used to calculate the player's overall rating.

### 66. W/F

Player's weak foot rating (out of 5)

In [65]:
fifa21['W/F'].unique()

array(['4 ★', '3 ★', '5 ★', '2 ★', '1 ★'], dtype=object)

In [66]:
fifa21['W/F']=fifa21['W/F'].str.replace('★',"")

In [67]:
fifa21['W/F'].unique()

array(['4 ', '3 ', '5 ', '2 ', '1 '], dtype=object)

### 67. SM

Player's skill moves rating (out of 5)

In [68]:
fifa21['SM'].unique()

array(['4★', '5★', '1★', '2★', '3★'], dtype=object)

In [69]:
fifa21['SM']=fifa21['SM'].str.replace('★',"")

In [70]:
fifa21['SM'].unique()

array(['4', '5', '1', '2', '3'], dtype=object)

### 68. A/W

Player's attacking work rate (low, medium or high)

In [71]:
fifa21['A/W'].unique()

array(['Medium', 'High', 'Low'], dtype=object)

### 69. D/W

Player's defensive work rate (low, medium or high)

In [72]:
fifa21['D/W'].unique()

array(['Low', 'Medium', 'High'], dtype=object)

### 70. IR

Player's injury resistance rating (out of 3)

In [73]:
fifa21['IR'].unique()

array(['5 ★', '3 ★', '4 ★', '2 ★', '1 ★'], dtype=object)

In [74]:
fifa21['IR']=fifa21['IR'].str.replace('★',"")
fifa21['IR'].unique()

array(['5 ', '3 ', '4 ', '2 ', '1 '], dtype=object)

### 71. PAC

Player's pace attribute rating(0-100).

It measures the player's speed on the pitch, including their acceleration and sprinting ability. 

A higher PAC value indicates that the player is faster.

In [75]:
fifa21['PAC'].unique()

array([85, 89, 87, 76, 91, 78, 93, 86, 96, 88, 94, 65, 84, 74, 71, 77, 68,
       75, 54, 79, 83, 80, 81, 82, 63, 67, 90, 66, 42, 73, 70, 64, 57, 58,
       69, 72, 50, 59, 92, 60, 62, 55, 52, 56, 61, 53, 45, 37, 95, 43, 44,
       46, 48, 49, 47, 34, 39, 40, 51, 41, 36, 32, 33, 30, 31, 38, 35, 28,
       29, 25], dtype=int64)

### 72. SHO

Player's shooting attribute rating.(0-100)

In [76]:
fifa21['SHO'].unique()

array([92, 93, 86, 85, 91, 88, 60, 73, 89, 87, 70, 90, 81, 66, 72, 82, 28,
       74, 77, 62, 50, 83, 69, 80, 46, 76, 54, 49, 61, 58, 79, 68, 59, 41,
       45, 64, 78, 55, 75, 65, 63, 48, 42, 56, 51, 30, 47, 84, 40, 57, 25,
       71, 37, 43, 53, 67, 38, 52, 39, 35, 36, 44, 32, 34, 33, 31, 27, 22,
       29, 26, 23, 18, 24, 20, 16, 21, 19, 17], dtype=int64)

### 73. PAS

Player's passing attribute rating.(0-100)

In [77]:
fifa21['PAS'].unique()

array([91, 81, 78, 93, 86, 85, 88, 71, 80, 76, 74, 77, 79, 84, 73, 55, 83,
       87, 72, 75, 58, 89, 82, 68, 67, 64, 66, 59, 69, 90, 65, 53, 63, 62,
       70, 56, 42, 54, 61, 57, 60, 48, 52, 47, 46, 44, 45, 50, 51, 49, 43,
       36, 38, 40, 41, 35, 39, 34, 33, 37, 30, 32, 29, 31, 26, 28, 25, 27],
      dtype=int64)

### 74. DRI

Player's dribbling attribute rating.(0-100)

In [78]:
fifa21['DRI'].unique()

array([95, 89, 90, 88, 94, 85, 91, 71, 72, 86, 73, 81, 84, 92, 80, 68, 77,
       87, 60, 83, 78, 64, 67, 79, 69, 66, 65, 70, 82, 75, 61, 74, 54, 76,
       49, 63, 59, 62, 56, 55, 50, 57, 58, 52, 53, 51, 48, 47, 46, 39, 44,
       43, 36, 40, 45, 41, 37, 34, 35, 42, 32, 38, 31, 33, 30, 29, 28, 25,
       27], dtype=int64)

### 75. DEF

Player's defending attribute rating.

In [79]:
fifa21['DEF'].unique()

array([38, 35, 52, 64, 36, 43, 45, 51, 39, 91, 44, 86, 48, 57, 40, 88, 33,
       81, 63, 47, 53, 89, 71, 37, 80, 68, 85, 61, 90, 83, 49, 56, 58, 82,
       87, 79, 66, 55, 78, 32, 50, 76, 77, 70, 75, 41, 29, 73, 65, 59, 84,
       54, 72, 46, 42, 69, 34, 31, 30, 74, 24, 62, 25, 20, 26, 60, 27, 23,
       28, 67, 22, 19, 18, 21, 17, 15, 16, 12], dtype=int64)

### 76. PHY

Player's physical attribute rating.

In [80]:
fifa21['PHY'].dtype

dtype('int64')

### 77. Hits

Number of times the player has been searched for in the FIFA database.

In [81]:
fifa21['Hits'].unique()

array(['771', '562', '150', '207', '595', '248', '246', '120', '1.6K',
       '130', '321', '189', '175', '96', '118', '216', '212', '154',
       '205', '202', '339', '408', '103', '332', '86', '173', '161',
       '396', '1.1K', '433', '242', '206', '177', '1.5K', '198', '459',
       '117', '119', '209', '84', '187', '165', '203', '65', '336', '126',
       '313', '124', '145', '538', '182', '101', '45', '377', '99', '194',
       '403', '414', '593', '374', '245', '3.2K', '266', '299', '309',
       '215', '265', '211', '112', '337', '70', '159', '688', '116', '63',
       '144', '123', '71', '224', '113', '168', '61', '89', '137', '278',
       '75', '148', '176', '197', '264', '214', '247', '402', '440',
       '1.7K', '2.3K', '171', '320', '657', '87', '259', '200', '255',
       '253', '196', '60', '97', '85', '169', '256', '132', '239', '166',
       '121', '109', '32', '46', '122', '48', '527', '199', '282', '51',
       '1.9K', '642', '155', '323', '288', '497', '509', '79',

In [82]:
# def convert_hits(hit):
#     if 'K' in hit:
#         hits=hit.strip("K")*1000
#         return hits
# fifa21['Hits']=fifa21['Hits'].apply(convert_hits)
# fifa21['Hits'].unique()

In [83]:
fifa21.to_csv('fifa21 cleaned output.csv', encoding='utf-8')